### ISSUE TITLE
About the stylized dataset

### ISSUE THREAD

**Issue by annopackage** [bethgelab/robust-detection-benchmark#3]
Hi, thanks for your great work.

I wonder how to choose the num-styles while making stylized dataset. Could you provide the stylized COCO data used in your paper?

**Comment by rgeirhos** [comment]
If your question is referring to the num-styles parameter of https://github.com/bethgelab/stylize-datasets: we have used num-styles=1 throughout our experiments (one stylized image per original image).
Unfortunately, we cannot provide the entire COCO data but you may be able to create it yourself using https://github.com/bethgelab/stylize-datasets. Does this answer your question?

**Comment by annopackage** [comment]
Ok, I will have a try. BTW, which reference style do you use? I find there are different painters in https://www.kaggle.com/c/painter-by-numbers/data.

**Comment by rgeirhos** [comment]
We randomly sampled style images with the aim to use many different ones.

I'm closing this issue since the question seems resolved, please feel free to re-open if necessary!
