### ISSUE TITLE
Coco-C, Cityscape-C, Pascal-C dataset

### ISSUE THREAD

**Issue by AliNaqvi110** [bethgelab/robust-detection-benchmark#6]
Hi how can I download your Coco-C, Cityscape-C, and Pascal-C dataset with their labels. Actually I want to test my model on your dataset. I coudn't find a link to download.

**Comment by michaelisc** [comment]
Hi @AliNaqvi110, we compute the corruptions on-the-fly during evaluation and provide a toolbox for that: https://github.com/bethgelab/imagecorruptions. If your model is implemented in mmdetection, you can use the integrated evaluation script: https://github.com/open-mmlab/mmdetection/blob/master/docs/en/robustness_benchmarking.md.
