### ISSUE TITLE
Your paper question

### ISSUE THREAD

**Issue by jacob-kang** [bethgelab/robust-detection-benchmark#8]
Hello!
I have a question about your paper experiments (COCO only)

![image](https://user-images.githubusercontent.com/88817336/173389106-18c4ef4b-3135-426f-8ae0-4f93e5d69785.png)

In Table 2 and MS COCO column, I can understand you used clean COCO and COCO-C with ImageNet pretrained (maybe torchvision?)

![image](https://user-images.githubusercontent.com/88817336/173389608-517045d5-91fa-449e-b0e3-6c2849874a37.png)
But In Table 3 and MS COCO, The first one, train data IN, is different from Table 2.

I think the first row in the Table 2, It is trained on standard COCO with ImageNet pretrained.
And the the first row in the Table 3 as well, It is trained on standard COCO with ImageNet pretrained.

What is the difference between those?

Thanks.

**Comment by michaelisc** [comment]
See footnote 8 on page 8 in the [paper](https://arxiv.org/abs/1907.07484): 
> Note that Geirhos et al. [2019] use Faster R-CNN without Feature Pyramids (FPN), which is why the
baseline performance of these models is different from ours

For the experiments in Table 2 we use the standard architecture **with** FPN.
For the experiments in Table 3 we used the same model architecture as Geirhos et al. [2019] **without** FPN.

**Comment by jacob-kang** [comment]
Oh.... I didn't see the footnote.

Thanks!!!
