### ISSUE TITLE
Could you provide Combined dataset annotation for COCO?

### ISSUE THREAD

**Issue by jacob-kang** [bethgelab/robust-detection-benchmark#9]
hello!
I'm researching for robust detection.

I just made Stylized dataset for COCO.
But I want to benchmark your Combined dataset mAP.

Could you provide combined stylized dataset annotation please?

Thanks.

kind reagrds

**Comment by michaelisc** [comment]
Hello, we used [mmdetection](https://github.com/open-mmlab/mmdetection) for our experiments, where you can easily concatenate datasets by providing a list of datasets. You can check out the [base config for pascal voc 07+12](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/datasets/voc0712.py) for an example, how to combine datasets in the most recent version of mmdetection.

I am not sure if the same is possible with detectron2 or other frameworks. If not, you have to modify the annotation file to include the stylized images, however we never created such a file.
